apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: marloto/simple-express-js:v1.3
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app/config/
              name: demo-config-volume
              readOnly: true
      volumes:
        - name: demo-config-volume
          configMap:
            name: demo-config
            items:
              - key: config
                path: config.json
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: demo-ingress
spec:
    ingressClassName: nginx
    rules:
      - host: localhost
        http:
          paths:
            - backend:
                service:
                  name: demo
                  port:
                    number: 3000
              path: /
              pathType: Prefix