apiVersion: v1
kind: Pod
metadata:
  name: multi-container-example
spec:
  containers:
    - name: app1
      image: marloto/express-example
      ports:
        - containerPort: 3000
    - name: app2
      image: nginx:1.21
      ports:
        - containerPort: 80

