apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
    foo: bar


spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: marloto/express-example
          # build... ist hier nicht möglich
          # -> eigene registries verwenden, öffentlich bei open source 
          #    oder vergleichbar, andernfalls eigene Instanzen (vgl. AWS ECR)
          # -> lokal ggf. docker build -t marloto/express-example .
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "10Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3