# Docker Mount von Host-Dateisystem-Ordnern od. Dateien in das Dateisystem des Containers
# Docker-Managed-Volumes, erhalten Namen und Docker speichert die entsprechend
# Definiert möglichen Speicher

apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/seb/Entwicklung/THI/Repositories/thi-snippets/cnd-snippets/ws-2023/19-more-k8s/data"